-- KFOKAM48 — schéma initial (source : docs/diagrammes/D2-modele-donnees.md)
-- PostgreSQL 16

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(120) NOT NULL
);

CREATE TABLE etudiant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(120) NOT NULL,
    promotion_id BIGINT NOT NULL REFERENCES promotion (id)
);

CREATE TABLE session (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(200) NOT NULL,
    code          VARCHAR(10)  NOT NULL UNIQUE,
    ouverture_at  TIMESTAMP    NOT NULL,
    expiration_at TIMESTAMP    NOT NULL,
    cloture_at    TIMESTAMP,
    promotion_id  BIGINT       NOT NULL REFERENCES promotion (id)
);

CREATE TABLE presence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT    NOT NULL REFERENCES session (id),
    etudiant_id BIGINT    NOT NULL REFERENCES etudiant (id),
    source      VARCHAR(12) NOT NULL CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    marquee_at  TIMESTAMP NOT NULL,
    -- RG15 : une seule présence par session et par étudiant
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id)
);

CREATE TABLE exercice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT      NOT NULL REFERENCES session (id),
    etudiant_id BIGINT      NOT NULL REFERENCES etudiant (id),
    lien        VARCHAR(500) NOT NULL,
    statut      VARCHAR(12) NOT NULL CHECK (statut IN ('EN_ATTENTE', 'RELU')),
    depose_at   TIMESTAMP   NOT NULL,
    -- Un seul exercice par session et par étudiant
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id)
);

CREATE TABLE relecture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT      NOT NULL REFERENCES exercice (id),
    relecteur_id BIGINT      NOT NULL REFERENCES etudiant (id),
    note         INTEGER     CHECK (note BETWEEN 0 AND 20),
    commentaire  VARCHAR(2000),
    rendue_at    TIMESTAMP,
    -- RG4 : un seul relecteur par exercice
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),
    -- RG3 : le relecteur n'est jamais l'auteur de l'exercice (garantie applicative,
    -- impossible à exprimer directement en SQL sans dénormaliser exercice)
    CONSTRAINT ck_relecture_not_null_commentaire_at_rendue CHECK (rendue_at IS NULL OR (note IS NOT NULL AND commentaire IS NOT NULL))
);

CREATE INDEX idx_session_promotion ON session (promotion_id);
CREATE INDEX idx_presence_session ON presence (session_id);
CREATE INDEX idx_exercice_session ON exercice (session_id);
CREATE INDEX idx_relecteur_relectures ON relecture (relecteur_id);
