-- MODULE 2 : realignement des colonnes identity apres les donnees de demo (V2).
-- Les inserts explicites d'ids dans V2 n'avancent pas les sequences : sans ce
-- correctif, le prochain insert (session id=1) violerait la cle primaire.
-- Syntaxe valable sur PostgreSQL et H2 pour les colonnes GENERATED BY DEFAULT AS IDENTITY.

ALTER TABLE promotion ALTER COLUMN id RESTART WITH 2;
ALTER TABLE etudiant  ALTER COLUMN id RESTART WITH 6;
ALTER TABLE session   ALTER COLUMN id RESTART WITH 3;
ALTER TABLE presence  ALTER COLUMN id RESTART WITH 5;
ALTER TABLE exercice  ALTER COLUMN id RESTART WITH 3;
ALTER TABLE relecture ALTER COLUMN id RESTART WITH 2;
