-- MODULE 7 (EF9/RG7) : historique des modifications de relecture.
-- Chaque modification d'une relecture déjà rendue (avant clôture de session)
-- conserve les anciennes et les nouvelles valeurs.

CREATE TABLE relecture_historique (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relecture_id       BIGINT       NOT NULL REFERENCES relecture (id),
    ancienne_note      INTEGER      CHECK (ancienne_note BETWEEN 0 AND 20),
    ancien_commentaire VARCHAR(2000),
    nouvelle_note      INTEGER      NOT NULL CHECK (nouvelle_note BETWEEN 0 AND 20),
    nouveau_commentaire VARCHAR(2000) NOT NULL,
    modifie_at         TIMESTAMP    NOT NULL
);

CREATE INDEX idx_historique_relecture ON relecture_historique (relecture_id);

-- Les sequences doivent suivre les ids explicites de V2 (comme V3)
ALTER TABLE relecture_historique ALTER COLUMN id RESTART WITH 1;
